from django.urls import path
from signin.views import (
    home,
    index,
    social_accounts,
    profile_view,
    post_success,
    post,
    schedule_post,
    tauth,
    taccess,
    linkedin,
    facebook_auth,
    facebook_access,
    facebok_page_access,
    instabasic,
    facebok_page_access,
    insta_auth,
)

urlpatterns = [
    path("Twitter", tauth, name="Twitter_auth"),
    path("Taccess", taccess, name="access-token"),
    path("Linkedin_auth", linkedin, name="linkedin"),
    path("facebook_auth/", facebook_auth, name="facebook_auth"),
    path("facebook_access/", facebook_access, name="facebook_access"),
    path("insta_auth", insta_auth, name="insta_auth"),
    path("page_access", facebok_page_access),
    path("", home),
    path("page_access", facebok_page_access),
    path("page_access", facebok_page_access),
    path("page_access", facebok_page_access),
    # # path('logout', views.logout_view),
    path("index", index),
    path("post", post),
    path("social_account", social_accounts),
    path("profile", profile_view),
    path("post_success", post_success),
    path("schedule-post", schedule_post),
    path("", home),
]
