[
    {
        "id": 3,
        "provider": "google",
        "provider_id": "",
        "name": "google",
        "client_id": "122809078024-l4oq4reup8p76kntv8rs0b9bts4sgt6v.apps.googleusercontent.com",
        "secret": "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",
        "key": "AIzaSyDsQ3XHNO3CO9-sMaazogMWmxyRoPcSTVI",
        "settings": {},
    },
    {
        "id": 4,
        "provider": "facebook",
        "provider_id": "",
        "name": "facebook",
        "client_id": "901647908422952",
        "secret": "acd41f193030e7f7e366d11b7659b871",
        "key": "",
        "settings": {},
    },
    {
        "id": 7,
        "provider": "linkedin_oauth2",
        "provider_id": "",
        "name": "linkedin",
        "client_id": "86k979vfmusbph",
        "secret": "y6jJ8yWhbmEOGOOT",
        "key": "",
        "settings": {},
    },
    {
        "id": 8,
        "provider": "github",
        "provider_id": "",
        "name": "github",
        "client_id": "Iv1.720847ca221968b2",
        "secret": "c3dabc85ba0310470d2cc97e2ab00986a4cd1ff0",
        "key": "",
        "settings": {},
    },
    {
        "id": 9,
        "provider": "twitter_oauth2",
        "provider_id": "",
        "name": "twitter",
        "client_id": "f7cfLtcgOF6IjGu7FcpRcDJen",
        "secret": "V8ZW1wAlZBLZge0QeQ9zwdyVXHxqH0qct6pvMS5iORA00jFijB",
        "key": "",
        "settings": {},
    },
]
