# Generated by Django 4.2.9 on 2024-05-10 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Twitter_username", models.CharField(max_length=50)),
                ("social_media", models.CharField(max_length=20)),
                ("access_token", models.CharField(max_length=200)),
                ("access_token_secret", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialaccount.socialaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("post_text", models.CharField(max_length=100)),
                (
                    "post_media",
                    models.FileField(max_length=10485760, upload_to="post_media/"),
                ),
                ("twitter", models.BooleanField(default=False)),
                ("facebook", models.BooleanField(default=False)),
                ("instagram", models.BooleanField(default=False)),
                (
                    "post_date_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("post_type", models.CharField(max_length=20)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="signin.link"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Git",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialaccount.socialaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facebookuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=100)),
                ("page_id", models.IntegerField()),
                ("page_access_token", models.CharField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialaccount.socialaccount",
                    ),
                ),
            ],
        ),
    ]
