# Generated by Django 4.2.9 on 2024-05-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_schedule_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
