# Generated by Django 4.2.9 on 2024-03-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='Twitter_username',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
