# Generated by Django 4.2.9 on 2024-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_link_twitter_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebookuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=500)),
            ],
        ),
    ]
