# Generated by Django 4.2.9 on 2024-04-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_facebookuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='access_token',
            field=models.JSONField(),
        ),
    ]
