# Generated by Django 4.2.9 on 2024-04-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('signin', '0004_alter_facebookuser_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookuser',
            name='access_token',
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='page_access_token',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='page_id',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='page_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facebookuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount'),
        ),
    ]
