# Generated by Django 4.2.9 on 2024-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0004_remove_post_user_post_meta_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
