# Generated by Django 4.2.9 on 2024-05-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_media',
            field=models.ImageField(blank=True, max_length=10485760, null=True, upload_to='post_media/'),
        ),
    ]
