# Generated by Django 4.2.9 on 2024-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0005_remove_facebookuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='page_id',
            field=models.IntegerField(),
        ),
    ]
