# Generated by Django 4.2.9 on 2024-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0006_alter_facebookuser_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='social_media',
        ),
        migrations.AddField(
            model_name='post',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter',
            field=models.BooleanField(default=False),
        ),
    ]
